---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv-volume
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/cache"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi